### ISSUE TITLE
any plans to upload to npm?

### ISSUE THREAD

**Issue by psteinroe** [supabase-community/sentry-integration-js#1]
hey, thanks for the package! would love to use it, but it does not seem to be on npm yet. do you plan to release it?

**Comment by kamilogorek** [comment]
Hey, yes! Some time after x-mas, just need to dogfood it more.
Have you tried it already? Do you have any feedback or feature requests/ideas? :)

**Comment by coreyward** [comment]
+1 on NPM—you can put it under an alpha or beta release channel if you prefer to too, or just release as a pre-v1 version? 

I presume this is integrating with the new query performance tracking with Sentry, but the README doesn't quite confirm it for me. Is that what's going on, or would I still need to set that up separately with Slonik middleware?

🙏

**Comment by kamilogorek** [comment]
I'm OOO till Wednesday, so won't have access to our org registry, but till then, you can simply download a raw file from https://github.com/kamilogorek/supabase-sentry-integration/blob/master/index.js to use it as-is, as it's "no build required" :)

**Comment by gorkabalm** [comment]
I would love to use it via NPM too 🙏

**Comment by kamilogorek** [comment]
https://npmjs.com/@supabase/sentry-js-integration
https://github.com/supabase-community/sentry-integration-js/releases/tag/0.1.0

Excuse me such a long delay. Initial version has been published to npm/GitHub :)
