### ISSUE TITLE
Named export 'SupabaseClient' not found

### ISSUE THREAD

**Issue by Keagel** [supabase-community/sentry-integration-js#12]
# Bug report

## Describe the bug

`SupabaseClient` cannot be imported as a module in a server (node) context:

```
[vite] Error when evaluating SSR module /src/hooks.server.ts: failed to import "@supabase/supabase-js"
|- SyntaxError: [vite] Named export 'SupabaseClient' not found. The requested module '@supabase/supabase-js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@supabase/supabase-js';
const {SupabaseClient} = pkg;

    at analyzeImportedModDifference (file://node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:54049:19)
    at nodeImport (file://node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:55101:9)
    at async ssrImport (file://node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:54998:24)
    at async eval (src/hooks.server.ts:5:31)
    at async instantiateModule (file://node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:55058:9)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```bash
npm create svelte@latest supabase-test
cd supabase-test
npm install @supabase/sentry-js-integration@0.1.0 @supabase/supabase-js@2.43.2 @sentry/sveltekit@7.112.2
```

Add this code to the `hooks.server.ts` file in `src`:

```ts
import * as Sentry from '@sentry/sveltekit';
import { SupabaseIntegration } from '@supabase/sentry-js-integration';
import { SupabaseClient } from '@supabase/supabase-js';

Sentry.init({
    dsn: '',
    integrations: [
        new SupabaseIntegration(SupabaseClient, {
            tracing: true,
            breadcrumbs: true,
            errors: true
        })
    ]
});
```

## Expected behavior

`SupabaseClient` can be imported.

## Additional context

This can be solved by importing `SupabaseClient` like this:

```ts
import * as Sentry from '@sentry/sveltekit';
import { SupabaseIntegration } from '@supabase/sentry-js-integration';
import SupabaseClient from '@supabase/supabase-js';

Sentry.init({
    dsn: '',
    tracesSampleRate: 1,
    integrations: [
        new SupabaseIntegration(SupabaseClient.SupabaseClient, {
            tracing: true,
            breadcrumbs: true,
            errors: true
        })
    ]
});
```

It's more of a `supabase-js` issue (?) I assume, but I think it's worth adding a note about it in the docs of this repository as right now the usage in the README simply imports `SupabaseClient` as a module in both the client and server context.

**Comment by kamilogorek** [comment]
Did you try to use a version with `createClient` instead? It's how supabase-js is documented everywhere, and I made the integration with specifically with both possible approaches.

This is bundler-specific issue though, so as you said, other than documenting, there's not much to fix here.

**Comment by Keagel** [comment]
Since I'm using the [Supabase SSR approach](https://supabase.com/docs/guides/auth/server-side/creating-a-client?queryGroups=framework&framework=sveltekit#creating-a-client), `createServerClient` is used instead of `createClient` and that generates a TS warning:

```
Argument of type 'SupabaseClient<Database, SchemaName, Schema>' is not assignable to parameter of type 'typeof SupabaseClient'.
  Property 'prototype' is missing in type 'SupabaseClient<Database, SchemaName, Schema>' but required in type 'typeof SupabaseClient'
```

I settled on the version in the first post as it didn't generate a warning. Just figured it would be worth mentioning in the docs since I wasn't sure if something was wrong with my setup.

**Comment by kamilogorek** [comment]
> I settled on the version in the first post as it didn't generate a warning. Just figured it would be worth mentioning in the docs since I wasn't sure if something was wrong with my setup.

I'll figure out how to make it work with SSR and update docs accordingly. Thanks for the report :)

**Comment by kamilogorek** [comment]
I dropped type requirement from integration constructor. It brings close to no additional value and can be annoying in case anything changes in the exported Supabase SDK type.
