### ISSUE TITLE
Docs out of sync with Github README regarding NextJS

### ISSUE THREAD

**Issue by harrybawsac** [supabase-community/sentry-integration-js#16]
# Improve documentation

## Link 

The [integration page for NextJS](https://supabase.com/docs/guides/platform/sentry-monitoring?queryGroups=package-manager&package-manager=yarn#example-nextjs-configuration) is providing different file examples as opposed to the README in Github.

## Describe the problem

For the `sentry.client.config.ts` file, the website says to use `Sentry.nativeNodeFetchIntegration`, while the README says to use `Sentry.browserTracingIntegration`.

For the `sentry.server.config.ts` file, the website says to use `Sentry.winterCGFetchIntegration`, while the README says to use `Sentry.nativeNodeFetchIntegration`.

For the `sentry.edge.config.ts` file, the website says to use `new Sentry.Integrations.WinterCGFetch` (which gives an error as it doesn't exist), while the README says to use `Sentry.winterCGFetchIntegration`.

## Describe the improvement

I guess the README is the correct one? As the one on the website gives an error on application startup.

**Comment by kamilogorek** [comment]
Yes, the readme is correct. Thanks for catching that!
Fixed in https://github.com/supabase/supabase/pull/28512
