### ISSUE TITLE
@supabase/sentry-js-integration triggers EDGE_FUNCTION_INVOCATION_FAILED

### ISSUE THREAD

**Issue by ollebergkvist** [supabase-community/sentry-integration-js#8]
# Bug report

## Describe the bug

After following docs and deploying app on Vercel, app crashes due to EDGE_FUNCTION_INVOCATION_FAILED.

The only thing that differs from my code and the code in the instructions is this:
```
 Sentry.browserTracingIntegration({
        shouldCreateSpanForRequest: (url) => {
          return !url.startsWith(`${NEXT_PUBLIC_SUPABASE_URL}/rest`)
        },
      }),
```

vs

```
new Sentry.BrowserTracing({
      shouldCreateSpanForRequest: (url) => {
        return !url.startsWith(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/rest`);
      },
    }),
```

BrowserTracing is deprecated.

sentry.client.config.ts 

```
if (isProduction()) {
  Sentry.init({
    dsn: DSN,
    tracesSampleRate: 0.3,
    debug: false,
    replaysOnErrorSampleRate: 1.0,
    replaysSessionSampleRate: 0.1,
    integrations: [
      Sentry.replayIntegration({
        maskAllText: true,
        blockAllMedia: true,
        unmask: ['header', 'footer', 'nav'],
        networkDetailAllowUrls: [window.location.origin],
        networkDetailDenyUrls: [
          window.location.origin + '/_next/',
          window.location.origin + '/monitoring/',
        ],
        networkCaptureBodies: true,
      }),
      new SupabaseIntegration(SupabaseClient, {
        tracing: true,
        breadcrumbs: true,
        errors: true,
      }),
      Sentry.browserTracingIntegration({
        shouldCreateSpanForRequest: (url) => {
          return !url.startsWith(`${NEXT_PUBLIC_SUPABASE_URL}/rest`)
        },
      }),
    ],
    ignoreErrors: [],
  })
}
```

sentry.edge.config.ts
```
if (isProduction()) {
  Sentry.init({
    dsn: DSN,
    tracesSampleRate: 0.5,
    debug: false,
    integrations: [
      new SupabaseIntegration(SupabaseClient, {
        tracing: true,
        breadcrumbs: true,
        errors: true,
      }),
      new Sentry.Integrations.WinterCGFetch({
        breadcrumbs: true,
        shouldCreateSpanForRequest: (url) => {
          return !url.startsWith(`${NEXT_PUBLIC_SUPABASE_URL}/rest`)
        },
      }),
    ],
  })
}
```

sentry.server.config.ts
```
if (isProduction()) {
  Sentry.init({
    dsn: DSN,
    tracesSampleRate: 0.5,
    debug: false,
    integrations: [
      new SupabaseIntegration(SupabaseClient, {
        tracing: true,
        breadcrumbs: true,
        errors: true,
      }),
      new Sentry.Integrations.Undici({
        shouldCreateSpanForRequest: (url) => {
          return !url.startsWith(`${NEXT_PUBLIC_SUPABASE_URL}/rest`)
        },
      }),
    ],
    ignoreErrors: ['AuthApiError: code challenge does not match previously saved code verifier'],
  })
}
```

## Expected behavior

Should not crash in production.

## Screenshots

![Screenshot 2024-05-07 at 10 19 52](https://github.com/supabase-community/sentry-integration-js/assets/50720954/238683ea-33b7-457c-ba13-731373cd67a1)

## System information

  System:
    OS: macOS 12.7.4
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 7.17 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.asdf/installs/nodejs/lts/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.5.1 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 9.0.6 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.119
    Safari: 17.4.1
  npmPackages:
    @supabase/sentry-js-integration: ^0.1.0 => 0.1.0 
    @supabase/ssr: ^0.0.10 => 0.0.10 
    @supabase/supabase-js: ^2.39.3 => 2.43.1 
    next: ^14.2.3 => 14.2.3 
    supabase: ^1.136.3 => 1.165.0 

## Additional context

TypeError: Cannot create proxy with a non-object as target or handler
    at (../../node_modules/.pnpm/@supabase+sentry-js-integration@0.1.0_@supabase+supabase-js@2.39.3/node_modules/@supabase/sentry-js-integration/index.js:188:0)
    at (../../node_modules/.pnpm/@supabase+sentry-js-integration@0.1.0_@supabase+supabase-js@2.39.3/node_modules/@supabase/sentry-js-integration/index.js:165:0)
    at (../../node_modules/.pnpm/@sentry+core@7.112.2/node_modules/@sentry/core/esm/integration.js:114:0)
    at (../../node_modules/.pnpm/@sentry+core@7.112.2/node_modules/@sentry/core/esm/integration.js:84:0)
    at (../../node_modules/.pnpm/@sentry+core@7.112.2/node_modules/@sentry/core/esm/integration.js:81:0)
    at (../../node_modules/.pnpm/@sentry+core@7.112.2/node_modules/@sentry/core/esm/baseclient.js:422:42)
    at (../../node_modules/.pnpm/@sentry+core@7.112.2/node_modules/@sentry/core/esm/baseclient.js:270:0)
    at (../../node_modules/.pnpm/@sentry+core@7.112.2/node_modules/@sentry/core/esm/sdk.js:56:0)
    at (../../node_modules/.pnpm/@sentry+vercel-edge@7.112.2/node_modules/@sentry/vercel-edge/esm/sdk.js:75:14)

**Comment by kamilogorek** [comment]
Is there any chance that you can boil it down to a small repro that I can reuse to debug this?

Your dependency is listed as `2.39.3`, which is one of few patch releases that broke the integration (2.39.1-2.39.6 were broken), although it _should_ resolve to `2.43.1`, maybe there's an issue with that. Can you try to update the supabase-js first?
